/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Airplane;
import Business.AirlinerDirectory;
import Business.Airplane;
import Business.User.Airliner;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sayu
 */
public class AddAirplane extends javax.swing.JPanel {

    /**
     * Creates new form AddAirplane
     */
    private JPanel CardSequenceJPanel;
    private Airliner a;
 
    AddAirplane(JPanel CardSequenceJPanel, Airliner a) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.a=a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAirplaneName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtWingSpan = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        txtEngine = new javax.swing.JTextField();
        txtLength = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        txtSeatingCapacity = new javax.swing.JTextField();
        txtCabinWidth = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnLoadDatas = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CREATE AIRPLANE ");

        jLabel8.setText("Airplane Name:");

        txtAirplaneName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirplaneNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Seating Capacity:");

        jLabel4.setText("Engine Type:");

        jLabel6.setText("Height of Airplane (m):");

        jLabel7.setText("Wing span of Airplane (m):");

        jLabel5.setText("Length of Airplane (m) :");

        txtWingSpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWingSpanActionPerformed(evt);
            }
        });

        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });

        txtEngine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEngineActionPerformed(evt);
            }
        });

        txtLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLengthActionPerformed(evt);
            }
        });

        btnCreate.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        backBtn.setText("< BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        txtSeatingCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatingCapacityActionPerformed(evt);
            }
        });

        txtCabinWidth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCabinWidthActionPerformed(evt);
            }
        });

        jLabel9.setText("Cabin Width (m):");

        btnLoadDatas.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        btnLoadDatas.setText("Load Data");
        btnLoadDatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadDatasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAirplaneName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8))
                                .addGap(109, 109, 109)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEngine)
                                    .addComponent(txtLength)
                                    .addComponent(txtHeight, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtWingSpan, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCabinWidth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtSeatingCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(btnLoadDatas)
                                .addGap(42, 42, 42)))))
                .addContainerGap(250, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(307, 307, 307))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(backBtn)
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSeatingCapacity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAirplaneName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEngine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWingSpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCabinWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoadDatas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(144, 144, 144))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAirplaneNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirplaneNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirplaneNameActionPerformed

    private void txtWingSpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWingSpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWingSpanActionPerformed

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed

    private void txtEngineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEngineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEngineActionPerformed

    private void txtLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLengthActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String airlineName = txtAirplaneName.getText();
        if(airlineName==null || airlineName.equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter proper Airplane Name");
            return;
        }
        
        String seating=txtSeatingCapacity.getText();
            try{
            Integer.parseInt(seating);
            }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please type in a number for Seat Capacity");
            return;}
      //  int seating = Integer.parseInt(txtSeatingCapacity.getText());
        
        String engine = txtEngine.getText();
        if(engine==null || engine.equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter proper engine details");
            return;
        }
        
        String wingSpan = txtWingSpan.getText();
        if(wingSpan==null || engine.equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter proper wing span");
            return;
        }

        String length = txtLength.getText();
        if(length==null || length.equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter proper length");
            return;
        }

        String height = txtHeight.getText();
        if(height==null || height.equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter proper height");
            return;
        }

        String cabinWidth = txtCabinWidth.getText();
        if(cabinWidth==null || cabinWidth.equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter proper cabin width");
            return;
        }
        
       

        Airplane p = a.getAirplaneDirectory().addAirplane();
        p.setAirplaneName(airlineName);
        p.setSeatingCapacity(Integer.parseInt(seating));
        p.setEngine(engine);
        p.setLength(length);
        p.setHeight(height);
        p.setWingspan(wingSpan);
        p.setCabinWidth(cabinWidth);

        JOptionPane.showMessageDialog(null, "Airplane Created Successfully");
        
        
        txtCabinWidth.setText("");
        txtHeight.setText("");
        txtLength.setText("");
        txtWingSpan.setText(""); 
        txtEngine.setText("");
        txtAirplaneName.setText("");
        txtSeatingCapacity.setText("");
    }//GEN-LAST:event_btnCreateActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        Component[] componentArray = CardSequenceJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageAirplane manageAirplane = (ManageAirplane) component;
        manageAirplane.populateTable();
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.previous(CardSequenceJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void txtSeatingCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeatingCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeatingCapacityActionPerformed

    private void txtCabinWidthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCabinWidthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCabinWidthActionPerformed

    private void btnLoadDatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadDatasActionPerformed
        // TODO add your handling code here:
         String filepath = "C:\\Users\\anjal\\Documents\\NetBeansProjects\\Assignment4\\Emirates.csv";
         File file = new File(filepath);
         String line =null;
         String name;
         int seat;
         String Engine;
         String Length;           
         String Height ;  
         String wingspan;
         String cabinsize;              
         
         
         
        
              
              BufferedReader br;
        try {
            br = new BufferedReader(new FileReader(file));
        
              
             for(int  i=0;i<10;i++)
        {
              while((line = br.readLine()) != null ){
                String[] temp = line.split(",");
                name=temp[0];
                seat=Integer.parseInt(temp[1]);
                Engine=temp[2];
                Length=temp[3];
                Height=temp[4];
                wingspan=temp[5];
                cabinsize=temp[6];
               
                

                  Airplane p = a.getAirplaneDirectory().addAirplane();
                  p.setAirplaneName(name);
                  p.setSeatingCapacity(seat);
                  p.setEngine(Engine);
                  p.setLength(Length);
                  p.setHeight(Height);
                  p.setWingspan(wingspan);
                  p.setCabinWidth(cabinsize);
                
              }      
             
         }} catch (FileNotFoundException ex) {
            Logger.getLogger(AddAirplane.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AddAirplane.class.getName()).log(Level.SEVERE, null, ex);
        }
              
    
    JOptionPane.showMessageDialog(null, "Data Successfully Loaded");
        
    }//GEN-LAST:event_btnLoadDatasActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnLoadDatas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAirplaneName;
    private javax.swing.JTextField txtCabinWidth;
    private javax.swing.JTextField txtEngine;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtSeatingCapacity;
    private javax.swing.JTextField txtWingSpan;
    // End of variables declaration//GEN-END:variables
}
