/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Airplane;
import UserInterface.Airplane.AddAirplane;
import Business.AirlinerDirectory;
import Business.Airplane;
import Business.AirplaneDirectory;
import Business.User.Airliner;
import UserInterface.Flight.ManageFlight;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sayu
 */
public class ManageAirplane extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirplane
     */
    private JPanel userProcessContainer;
    private Airliner airliner;
  public ManageAirplane(JPanel upc, Airliner airliner) {
         initComponents();
        userProcessContainer = upc;
        this.airliner = airliner;
        txtAirline.setText(airliner.getAirlineName());
         populateTable();

    }
public void populateTable()
    {
       
        int rowCount = tblAirplane.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel) tblAirplane.getModel();
        dtm.setRowCount(0);
         
        for(Airplane a : airliner.getAirplaneDirectory().getAirplaneList()){
        {
            Object [] row = new Object[8];
            row[0]=a;     
            row[1]=a.getSeatingCapacity();
            row[2]=a.getEngine();
            row[3]=a.getLength();
            row[4]=a.getHeight();
            row[5]=a.getWingspan();
            row[6]=a.getCabinWidth();
            
            dtm.addRow(row); 
        }
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAirplane = new javax.swing.JTable();
        btnAddAirplane = new javax.swing.JButton();
        btnViewAirplane = new javax.swing.JButton();
        btnDeleteAirplane = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAirline = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(650, 734));

        tblAirplane.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "SeatCapacity", "Engine", "Length", "Height", "Wingspan", "CabinWidth"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAirplane);
        if (tblAirplane.getColumnModel().getColumnCount() > 0) {
            tblAirplane.getColumnModel().getColumn(0).setResizable(false);
            tblAirplane.getColumnModel().getColumn(1).setResizable(false);
            tblAirplane.getColumnModel().getColumn(2).setResizable(false);
            tblAirplane.getColumnModel().getColumn(3).setResizable(false);
            tblAirplane.getColumnModel().getColumn(4).setResizable(false);
            tblAirplane.getColumnModel().getColumn(5).setResizable(false);
            tblAirplane.getColumnModel().getColumn(6).setResizable(false);
        }

        btnAddAirplane.setText("ADD Airplane");
        btnAddAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAirplaneActionPerformed(evt);
            }
        });

        btnViewAirplane.setText("VIEW Airplane");
        btnViewAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAirplaneActionPerformed(evt);
            }
        });

        btnDeleteAirplane.setText("DELETE Airplane");
        btnDeleteAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAirplaneActionPerformed(evt);
            }
        });

        backBtn.setText("< BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Airliner:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manage Airplane Fleet ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(txtAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAddAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnViewAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(89, 89, 89)
                                    .addComponent(btnDeleteAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(backBtn)
                .addGap(61, 61, 61)
                .addComponent(jLabel2)
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAirline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteAirplane)
                    .addComponent(btnViewAirplane)
                    .addComponent(btnAddAirplane))
                .addContainerGap(345, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAirplaneActionPerformed
        // TODO add your handling code here:

        AddAirplane panel = new AddAirplane(userProcessContainer,airliner);
        userProcessContainer.add("AddFlight",panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddAirplaneActionPerformed

    private void btnViewAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAirplaneActionPerformed
        // TODO add your handling code here:

        int selectedRow =  tblAirplane.getSelectedRow();
        if(selectedRow <0)
        {
            JOptionPane.showMessageDialog(null,"Pleasse select a row","Warning", JOptionPane.WARNING_MESSAGE);

        }

        else
        {
            Airplane f =(Airplane) tblAirplane.getValueAt(selectedRow,0);

            ViewAirplane panel = new ViewAirplane(userProcessContainer,f);
            userProcessContainer.add("ViewAirplane",panel);
            CardLayout layout =(CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);

        }
    }//GEN-LAST:event_btnViewAirplaneActionPerformed

    private void btnDeleteAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAirplaneActionPerformed
        // TODO add your handling code here:
        int selectedRow =  tblAirplane.getSelectedRow();
        if(selectedRow >=0)
        {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult= JOptionPane.showConfirmDialog(null,"Would you like to delete airplane details?","Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION)
            {
                Airplane f = (Airplane)tblAirplane.getValueAt(selectedRow,0);
                airliner.getAirplaneDirectory().deleteAirplane(f);
                populateTable();

            }
            else
            {
                JOptionPane.showMessageDialog(null,"Pleasse select a row","Warning", JOptionPane.WARNING_MESSAGE);

            }
        }
    }//GEN-LAST:event_btnDeleteAirplaneActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnAddAirplane;
    private javax.swing.JButton btnDeleteAirplane;
    private javax.swing.JButton btnViewAirplane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAirplane;
    private javax.swing.JTextField txtAirline;
    // End of variables declaration//GEN-END:variables
}
