/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelAgency;

import Business.AirlinerDirectory;
import Business.CustomerDirectory;
import Business.Flight;
import Business.User.Airliner;
import Business.User.Customer;
import UserInterface.Flight.ViewFlight;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


public class MasterTravelSchedule extends javax.swing.JPanel {

    /**
     * Creates new form MasterTravelSchedule
     */
    private JPanel CardSequenceJPanel;
    private AirlinerDirectory airlinerDirectory;
    private CustomerDirectory customerList;
    private String cuserid;
    
    public MasterTravelSchedule(JPanel CardSequenceJPanel,AirlinerDirectory airlinerDirectory,CustomerDirectory customerList,String cuserid) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.airlinerDirectory=airlinerDirectory;
        this.customerList =customerList;
        this.cuserid = cuserid;
        populateTable();
    }
    
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblSearch.getModel();
        model.setRowCount(0);
       for (Airliner airliner : airlinerDirectory.getAirliners()) {
           {
        for (Flight f : airliner.getFlightSchedule().getFlightList()){
            Object row[] = new Object[10];
            row[0] = f;
            row[1] = f.getOrigin();
            row[2] = f.getDestination();
            DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            row[3] = format.format(f.getFlightDate());
            row[4] = f.getFlightDuration();
            row[5] = f.getTicketPrice();
            row[6] = f.getPreferedTime();
            row[7] = airliner;
            model.addRow(row);
        }
           }
       }
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearch = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnSearchProduct = new javax.swing.JButton();
        txtDate = new javax.swing.JTextField();
        btnSearchProduct2 = new javax.swing.JButton();
        txtFlightNumber = new javax.swing.JTextField();
        txtFrom = new javax.swing.JTextField();
        btnSearchProduct4 = new javax.swing.JButton();
        txtTo = new javax.swing.JTextField();
        btnSearchProduct5 = new javax.swing.JButton();
        btnSearchProduct1 = new javax.swing.JButton();
        ComboBoxTime = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SEARCH FLIGHTS");

        btnBack.setText("<-Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FlightNo.", "From", "To", "Date", "Duration", "Price", "Time", "Airliner"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSearch);
        if (tblSearch.getColumnModel().getColumnCount() > 0) {
            tblSearch.getColumnModel().getColumn(0).setResizable(false);
            tblSearch.getColumnModel().getColumn(1).setResizable(false);
            tblSearch.getColumnModel().getColumn(2).setResizable(false);
            tblSearch.getColumnModel().getColumn(3).setResizable(false);
            tblSearch.getColumnModel().getColumn(4).setResizable(false);
            tblSearch.getColumnModel().getColumn(5).setResizable(false);
            tblSearch.getColumnModel().getColumn(6).setResizable(false);
            tblSearch.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Flights:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        btnSearchProduct.setText("From:");
        btnSearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProductActionPerformed(evt);
            }
        });

        btnSearchProduct2.setText("To");
        btnSearchProduct2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProduct2ActionPerformed(evt);
            }
        });

        btnSearchProduct4.setText("Flight Number:");
        btnSearchProduct4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProduct4ActionPerformed(evt);
            }
        });

        btnSearchProduct5.setText("Date:");
        btnSearchProduct5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProduct5ActionPerformed(evt);
            }
        });

        btnSearchProduct1.setText("Preferred time:");
        btnSearchProduct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProduct1ActionPerformed(evt);
            }
        });

        ComboBoxTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning", "Afternoon", "Evening", "Night" }));
        ComboBoxTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTimeActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnSearchProduct)
                            .addGap(18, 18, 18)
                            .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(btnSearchProduct2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(btnSearchProduct5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(btnSearchProduct1)
                            .addGap(18, 18, 18)
                            .addComponent(ComboBoxTime, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49)
                            .addComponent(btnSearchProduct4)
                            .addGap(18, 18, 18)
                            .addComponent(txtFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchProduct)
                    .addComponent(btnSearchProduct2)
                    .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchProduct5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchProduct4)
                    .addComponent(txtFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchProduct1))
                .addGap(41, 41, 41)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("View Flights");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(333, 333, 333))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(117, 117, 117)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchProductActionPerformed
      
    }//GEN-LAST:event_btnSearchProductActionPerformed

    private void btnSearchProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchProduct1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchProduct1ActionPerformed

    private void btnSearchProduct2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchProduct2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchProduct2ActionPerformed

    private void btnSearchProduct4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchProduct4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchProduct4ActionPerformed

    private void btnSearchProduct5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchProduct5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchProduct5ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        Flight from = null;
        Flight to = null;
        Flight flightNumber = null;
        Flight dates = null;
        String travelDate;
        Flight prefTime = null ;
        String error = "";
        int found =0;
        
        if((txtFrom.equals("")) && (txtTo.equals("")) && (txtFlightNumber.equals("")) && (txtDate.equals(""))){
          
            JOptionPane.showMessageDialog(null, "Please enter all the required details", "Information", JOptionPane.INFORMATION_MESSAGE);
            
        }
        
        else{
         
            found = 0;
            for (Airliner airliner : airlinerDirectory.getAirliners()) {
                if (found != 1) {
                    from = airliner.getFlightSchedule().searchFrom(txtFrom.getText());
                    to = airliner.getFlightSchedule().searchDestination(txtTo.getText());
                    flightNumber = airliner.getFlightSchedule().searchFlightNumber(txtFlightNumber.getText());
                    String dateFlight = txtDate.getText();
                    Object time = ComboBoxTime.getSelectedItem();
                    String prefferedtime = time.toString();
                    prefTime = airliner.getFlightSchedule().searchTime(prefferedtime);
                    DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                    System.out.println(airliner);
                    System.out.println(flightNumber);
                    System.out.println(from);
                    System.out.print(to);
                    try {
                        Date date = format.parse(dateFlight);
                        dates = airliner.getFlightSchedule().searchDate(date);
                    } catch (ParseException ex) {
                        Logger.getLogger(MasterTravelSchedule.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if ((from != null) && (to != null) && (flightNumber != null) && (dates != null) && (prefTime != null)) {
                    found = 1;
                }
            }

            if ((from == null) || (to == null) || (flightNumber == null) || (dates == null) || (prefTime == null)) {
                error = "No flights exists for the entered details";
                JOptionPane.showMessageDialog(null, error, "Information", JOptionPane.INFORMATION_MESSAGE);
               
            }
            else{
            
            Object time = ComboBoxTime.getSelectedItem();
            String prefferedtime = time.toString();
            String dateFlight = txtDate.getText();
            
            
            DefaultTableModel dtm = (DefaultTableModel)tblSearch.getModel(); 
            TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tblSearch.getModel());
            tblSearch.setRowSorter(rowSorter);
            List<RowFilter<Object, Object>> filters = new ArrayList<RowFilter<Object, Object>>(6);
            filters.add(RowFilter.regexFilter(txtFrom.getText().trim(),1));
            filters.add(RowFilter.regexFilter(txtTo.getText().trim(),2));
           filters.add(RowFilter.regexFilter(txtFlightNumber.getText().trim(),0));
            filters.add(RowFilter.regexFilter(dateFlight.trim(),3)); 
           filters.add(RowFilter.regexFilter(prefferedtime.trim(),6));
            RowFilter<Object, Object> rf = RowFilter.andFilter(filters);
            rowSorter.setRowFilter(rf);
            populateTable();
            
           }
        }
            
          
    }//GEN-LAST:event_btnSearchActionPerformed

    private void ComboBoxTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxTimeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow =  tblSearch.getSelectedRow();
        if(selectedRow <0)
        {
            JOptionPane.showMessageDialog(null,"Pleasse select a row","Warning", JOptionPane.WARNING_MESSAGE);

        }

        else
        {
            Flight f =(Flight) tblSearch.getValueAt(selectedRow,0);
            for(Customer c: customerList.getCustomers()){
                if(c.getUserName().equals(cuserid)){
            
            ViewFlight panel = new ViewFlight(CardSequenceJPanel,f,cuserid,customerList);
            CardSequenceJPanel.add("ViewFlight",panel);
            CardLayout layout =(CardLayout) CardSequenceJPanel.getLayout();
            layout.next(CardSequenceJPanel);
                }
        }
            ViewFlight panel = new ViewFlight(CardSequenceJPanel,f);
            CardSequenceJPanel.add("ViewFlight",panel);
            CardLayout layout =(CardLayout) CardSequenceJPanel.getLayout();
            layout.next(CardSequenceJPanel); 
        
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
         CardSequenceJPanel.remove(this);
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.previous( CardSequenceJPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxTime;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchProduct;
    private javax.swing.JButton btnSearchProduct1;
    private javax.swing.JButton btnSearchProduct2;
    private javax.swing.JButton btnSearchProduct4;
    private javax.swing.JButton btnSearchProduct5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSearch;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtFlightNumber;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
