/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.AbstractClasses.User;
import Business.AirlinerDirectory;
import Business.CustomerDirectory;
import Business.MasterSeatDirectory;
import Business.MasterTicketCatalog;
import Business.SeatDirectory;
import Business.User.Admin;
import Business.User.CustomerLog;
import Business.User.CustomerLoginDirectory;
import Business.User.TravelAgent;
import Business.User.TravelAgentDirectory;
import UserInterface.Airline.ManageAirline;
import UserInterface.Customer.CustomerLogin;
import UserInterface.TravelAgency.MasterTravelSchedule;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anjali
 */
public class Login extends javax.swing.JPanel {

    public TravelAgentDirectory agtDir;
    public CustomerLoginDirectory custLoginDir;
    private Admin admin;
    private String title;
    private AirlinerDirectory airlinerDirectory;
    private MasterSeatDirectory seatDirectory;
    private MasterTicketCatalog ticketDirectory;

    List<User> list;
    JPanel CardSequenceJPanel;
    
    public Login(JPanel CardSequenceJPanel, List<User> list,AirlinerDirectory airlinerDirectory) {
        
        custLoginDir = new CustomerLoginDirectory();
        seatDirectory = new MasterSeatDirectory();
        SeatDirectory sdA = new SeatDirectory("A");
        SeatDirectory sdB = new SeatDirectory("B");
        SeatDirectory sdC = new SeatDirectory("C");
        SeatDirectory sdD = new SeatDirectory("D");
        SeatDirectory sdE = new SeatDirectory("E");
        SeatDirectory sdF = new SeatDirectory("F");       
        seatDirectory.addSeatDirectory(sdA);
        seatDirectory.addSeatDirectory(sdB);
        seatDirectory.addSeatDirectory(sdC);
        seatDirectory.addSeatDirectory(sdD);
        seatDirectory.addSeatDirectory(sdE);
        seatDirectory.addSeatDirectory(sdF);
        
        ticketDirectory = new MasterTicketCatalog();
        
        initComponents();
        this.list = list;
        this.airlinerDirectory=airlinerDirectory;
        this.CardSequenceJPanel = CardSequenceJPanel;
        admin = new Admin();
        initialize();
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitle = new javax.swing.JLabel();
        comboUser = new javax.swing.JComboBox<>();
        txtPword = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        txtTitle.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtTitle.setText("Customer Login Screen");

        comboUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSubmit.setText("Login");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPword)
                                .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTitle)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(txtTitle)
                .addGap(139, 139, 139)
                .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if(title.equalsIgnoreCase("Customer"))
        {User u=(User) comboUser.getSelectedItem();
           
        if (u!=null)
            {CustomerLog c=(CustomerLog)u;
                if (c.verify(txtPword.getText())) {
                 CustomerLogin custPanel = new CustomerLogin(CardSequenceJPanel, custLoginDir, airlinerDirectory, seatDirectory, ticketDirectory, c);
                CardSequenceJPanel.add("CustomerLogin", custPanel);
                CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
                layout.next(CardSequenceJPanel);
                }
                else{
                    JOptionPane.showMessageDialog(null, " Password not correct");
                }

            }
        }
        if (title.equalsIgnoreCase("TravelAgent")) 
        {
            User u = (User) comboUser.getSelectedItem();

            if (u != null) {
                boolean x = airlinerDirectory.getAirliners().isEmpty();
                if(x==false){
                TravelAgent t = (TravelAgent) u;
                if (t.verify(txtPword.getText())) {
                    MasterTravelSchedule mastertravel = new MasterTravelSchedule(CardSequenceJPanel, airlinerDirectory);
                    CardSequenceJPanel.add("MasterTravelSchedule", mastertravel);
                    CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
                    layout.next(CardSequenceJPanel);
                }else{
                     JOptionPane.showMessageDialog(null, " Admin has not added Airliners, Please add airliners");
                }


                } else {
                    JOptionPane.showMessageDialog(null, " Password not correct");
                }

            }
        }
    }


    private void initialize(){
        if(list.get(0).getRole()==("Customer")){     
        txtTitle.setText("Customer Login Screen");
         title = "Customer";
        }else{
        txtTitle.setText("Travel Agent Login Screen");
             title = "TravelAgent";
    }
        comboUser.setModel(new DefaultComboBoxModel(list.toArray()));
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<Object> comboUser;
    private javax.swing.JTextField txtPword;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
