/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Airline;
import Business.AirlinerDirectory;
import Business.Airplane;
import Business.MasterSeatDirectory;
import Business.User.Airliner;
import UserInterface.Airline.ViewAirline;
import UserInterface.Airplane.AirplaneLogin;
import UserInterface.Airplane.ManageAirplane;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sayu
 */
public class ManageAirline extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirline
     */
 
private JPanel CardSequenceJPanel;
    private AirlinerDirectory airlinerDirectory;
    private MasterSeatDirectory sd;
    
   public ManageAirline(JPanel CardSequenceJPanel, AirlinerDirectory airlinerDirectory,MasterSeatDirectory sd) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.airlinerDirectory=airlinerDirectory;
        this.sd = sd;
        
        
       populateTable();

    }
    
    public void populateTable()
    {
        DefaultTableModel dtm = (DefaultTableModel) airlineScheduleTbl.getModel();
        dtm.setRowCount(0);
        
        for(Airliner a : airlinerDirectory.getAirliners())
        {
            Object [] row = new Object[2];
            row[0]=a;
            row[1]=a.getCountry();
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        airlineScheduleTbl = new javax.swing.JTable();
        addAirlinerBtn = new javax.swing.JButton();
        viewAirlinerBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        deleteAirlineBtn = new javax.swing.JButton();
        btnManageAirplane = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnManageFlights = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        airlineScheduleTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline Name", "Country of Origin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(airlineScheduleTbl);

        addAirlinerBtn.setText("Add Airliner");
        addAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAirlinerBtnActionPerformed(evt);
            }
        });

        viewAirlinerBtn.setText("View Airliner");
        viewAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAirlinerBtnActionPerformed(evt);
            }
        });

        backBtn.setText("< BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        deleteAirlineBtn.setText("Delete");
        deleteAirlineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAirlineBtnActionPerformed(evt);
            }
        });

        btnManageAirplane.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnManageAirplane.setText("Manage Airplanes ->");
        btnManageAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAirplaneActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAGE AIRLINER");

        btnManageFlights.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnManageFlights.setText("Manage Flights ->");
        btnManageFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFlightsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(addAirlinerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(52, 52, 52)
                                    .addComponent(viewAirlinerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(deleteAirlineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnManageAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnManageFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(backBtn)
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAirlinerBtn)
                    .addComponent(viewAirlinerBtn)
                    .addComponent(deleteAirlineBtn))
                .addGap(67, 67, 67)
                .addComponent(btnManageAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAirlinerBtnActionPerformed
        // TODO add your handling code here:
        AddAirline panel = new AddAirline(CardSequenceJPanel,airlinerDirectory);
        CardSequenceJPanel.add("AddAirline",panel);
        CardLayout layout =(CardLayout) CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_addAirlinerBtnActionPerformed

    private void viewAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAirlinerBtnActionPerformed
        // TODO add your handling code here:

        int selectedRow =  airlineScheduleTbl.getSelectedRow();
        if(selectedRow <0)
        {
            JOptionPane.showMessageDialog(null,"Pleasse select a row","Warning", JOptionPane.WARNING_MESSAGE);

        }

        else
        {
            Airliner a =(Airliner) airlineScheduleTbl.getValueAt(selectedRow,0);
            ViewAirline panel = new ViewAirline(CardSequenceJPanel,airlinerDirectory,a);
            CardSequenceJPanel.add("ViewAirline",panel);
            CardLayout layout =(CardLayout) CardSequenceJPanel.getLayout();
            layout.next(CardSequenceJPanel);

        }
    }//GEN-LAST:event_viewAirlinerBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
        layout.previous(CardSequenceJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void deleteAirlineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAirlineBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow =  airlineScheduleTbl.getSelectedRow();
        if(selectedRow >=0)
        {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult= JOptionPane.showConfirmDialog(null,"Would you like to delete airliner details?","Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION)
            {
                Airliner a = (Airliner)airlineScheduleTbl.getValueAt(selectedRow,0);
                airlinerDirectory.deleteAirline(a);
                populateTable();

            }
            else
            {
                JOptionPane.showMessageDialog(null,"Pleasse select a row","Warning", JOptionPane.WARNING_MESSAGE);

            }
        }
    }//GEN-LAST:event_deleteAirlineBtnActionPerformed

    private void btnManageAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAirplaneActionPerformed
        // TODO add your handling code here:

       
            AirlineLogin panel = new AirlineLogin(CardSequenceJPanel,airlinerDirectory);
            CardSequenceJPanel.add("AirlineLogin",panel);
            CardLayout layout =(CardLayout) CardSequenceJPanel.getLayout();
            layout.next(CardSequenceJPanel);

        

    }//GEN-LAST:event_btnManageAirplaneActionPerformed

    private void btnManageFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFlightsActionPerformed
        // TODO add your handling code here:
          AirplaneLogin panel = new AirplaneLogin(CardSequenceJPanel,airlinerDirectory,sd);
          CardSequenceJPanel.add("AirplaneLogin",panel);
          CardLayout layout =(CardLayout) CardSequenceJPanel.getLayout();
          layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnManageFlightsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAirlinerBtn;
    private javax.swing.JTable airlineScheduleTbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnManageAirplane;
    private javax.swing.JButton btnManageFlights;
    private javax.swing.JButton deleteAirlineBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewAirlinerBtn;
    // End of variables declaration//GEN-END:variables
}
