/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Flight;

import Business.CustomerDirectory;
import Business.Flight;
import Business.User.Customer;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anjali
 */
public class ViewFlight extends javax.swing.JPanel {

    /**
     * Creates new form ViewFlight
     */
    private JPanel CardSequenceJPanel;
    private Flight f;
    private CustomerDirectory customerList;
    
    public ViewFlight(JPanel upc,Flight f,String cuserid,CustomerDirectory customerList) {
        initComponents();
       
        this.f=f;
        this.CardSequenceJPanel = upc;
        this.customerList = customerList;
        flightUpdateBtn.setEnabled(true);
        flightSaveBtn.setEnabled(false);
        
        txtFlightNumber.setText(f.getFlightName());
        txtFrom.setText(f.getOrigin());
        txtTo.setText(f.getDestination());
        DateFormat formattime = new SimpleDateFormat("HH:mm ", Locale.ENGLISH);
        txtDeptTime.setText(formattime.format(f.getDestinationTime()));
        txtArrivalTime.setText(f.getArrivalTime());
        txtFlightDuration.setText(f.getFlightDuration());
        txtAirplane.setText(f.getAirplane());
        txtTicketPrice.setText(f.getTicketPrice());
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");  
        txtFlightDate.setText(dateFormat.format(f.getFlightDate()));
        txtCrewNumbers.setText(f.getCrewMembers());
        
        
        txtFlightNumber.setEnabled(false);
        txtFrom.setEnabled(false);
        txtTo.setEnabled(false);
        txtDeptTime.setEnabled(false);
        txtArrivalTime.setEnabled(false);
        txtFlightDuration.setEnabled(false);
        txtAirplane.setEnabled(false);
        txtTicketPrice.setEnabled(false);
        txtFlightDate.setEnabled(false);
                boolean checkCust = false;
        for(Customer c: customerList.getCustomers()){
            if(c.getUserName().equals(cuserid)){
                checkCust = true;
            }
        }
        if(checkCust){
            flightUpdateBtn.setEnabled(false);
        }
    }
    public ViewFlight(JPanel upc,Flight f) {
    initComponents();
       
        this.f=f;
        this.CardSequenceJPanel = upc;
        flightUpdateBtn.setEnabled(true);
        flightSaveBtn.setEnabled(false);
        
        txtFlightNumber.setText(f.getFlightName());
        txtFrom.setText(f.getOrigin());
        txtTo.setText(f.getDestination());
        DateFormat formattime = new SimpleDateFormat("HH:mm ", Locale.ENGLISH);
        txtDeptTime.setText(formattime.format(f.getDestinationTime()));
        txtArrivalTime.setText(f.getArrivalTime());
        txtFlightDuration.setText(f.getFlightDuration());
        txtAirplane.setText(f.getAirplane());
        txtTicketPrice.setText(f.getTicketPrice());
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");  
        txtFlightDate.setText(dateFormat.format(f.getFlightDate()));
        txtCrewNumbers.setText(f.getCrewMembers());
        
        
        txtFlightNumber.setEnabled(false);
        txtFrom.setEnabled(false);
        txtTo.setEnabled(false);
        txtDeptTime.setEnabled(false);
        txtArrivalTime.setEnabled(false);
        txtFlightDuration.setEnabled(false);
        txtAirplane.setEnabled(false);
        txtTicketPrice.setEnabled(false);
        txtFlightDate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTicketPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFlightNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAirplane = new javax.swing.JTextField();
        txtFlightDuration = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtArrivalTime = new javax.swing.JTextField();
        txtDeptTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTo = new javax.swing.JTextField();
        txtFrom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        flightSaveBtn = new javax.swing.JButton();
        flightUpdateBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtFlightDate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCrewNumbers = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 102, 102));

        txtTicketPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTicketPriceActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VIEW FLIGHT");

        jLabel8.setText("Flight Number:");

        txtFlightNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFlightNumberActionPerformed(evt);
            }
        });

        jLabel2.setText("Ticket Price:");

        jLabel9.setText("Number of Crew Members:");

        txtAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirplaneActionPerformed(evt);
            }
        });

        txtFlightDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFlightDurationActionPerformed(evt);
            }
        });

        jLabel7.setText("Flight Duration:");

        jLabel6.setText("Arrival Time:");

        txtArrivalTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArrivalTimeActionPerformed(evt);
            }
        });

        txtDeptTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeptTimeActionPerformed(evt);
            }
        });

        jLabel5.setText("Departure Time:");

        jLabel4.setText("To:");

        txtTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtToActionPerformed(evt);
            }
        });

        txtFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFromActionPerformed(evt);
            }
        });

        jLabel3.setText("From:");

        backBtn.setText("< BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        flightSaveBtn.setText("SAVE");
        flightSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightSaveBtnActionPerformed(evt);
            }
        });

        flightUpdateBtn.setText("UPDATE");
        flightUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightUpdateBtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Flight Date:");

        jLabel11.setText("Airplane:");

        txtCrewNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrewNumbersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(334, 334, 334))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(309, 309, 309)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDeptTime, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFlightDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFlightDate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTicketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCrewNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(66, 66, 66)
                                                .addComponent(jLabel8))
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(85, 85, 85)
                                            .addComponent(jLabel2))
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(68, 68, 68))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(flightSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)))
                            .addComponent(flightUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(488, 488, 488)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(backBtn)
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDeptTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFlightDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFlightDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTicketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtCrewNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(183, 183, 183))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTicketPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTicketPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTicketPriceActionPerformed

    private void txtFlightNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFlightNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFlightNumberActionPerformed

    private void txtAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirplaneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirplaneActionPerformed

    private void txtFlightDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFlightDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFlightDurationActionPerformed

    private void txtArrivalTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArrivalTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArrivalTimeActionPerformed

    private void txtDeptTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeptTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeptTimeActionPerformed

    private void txtToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtToActionPerformed

    private void txtFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFromActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.previous(CardSequenceJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void flightSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightSaveBtnActionPerformed
        // TODO add your handling code here:

        f.setFlightName(txtFlightNumber.getText());
        f.setOrigin(txtFrom.getText());
        f.setDestination(txtTo.getText());
        String arrivalTime = txtArrivalTime.getText();
        String deptTime = txtDeptTime.getText();
        
        f.setFlightDuration(txtFlightDuration.getText());
        f.setTicketPrice(txtTicketPrice.getText());
        f.setAirplane(txtAirplane.getText());
         f.setCrewMembers(txtCrewNumbers.getText()); 
         f.setArrivalTime(arrivalTime);
        String flightDate=txtFlightDate.getText();
        
        DateFormat formattime = new SimpleDateFormat("HH:mm");
        
         Date Dtime;
         
        try {
            Dtime = formattime.parse(deptTime);
            f.setDestinationTime(Dtime);
            Pattern p = Pattern.compile("^(2[0-3]|[01]?[0-9]):([0-5]?[0-9])$");
            Matcher m = p.matcher(deptTime);
            if (m.matches()) {
                String hourString = m.group(1);
                String minuteString = m.group(2);
                int hour = Integer.parseInt(hourString);
                int minute = Integer.parseInt(minuteString);
            if((hour>0) && (hour < 12)){
            f.setPreferedTime("Morning");
            }
            else if((hour>=12) && (hour<17)){
            f.setPreferedTime("Afternoon");
                    }
            else if((hour>=17) && (hour<20)){
            f.setPreferedTime("Evening");
                    }
            else if((hour>=20) && (hour<24)){
            f.setPreferedTime("Night");
                    }
            }
        } catch (ParseException ex) {
            Logger.getLogger(AddFlight.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        DateFormat format = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
        Date date;
        try {
            date = format.parse(flightDate);
            f.setFlightDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(AddFlight.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

        flightSaveBtn.setEnabled(false);
        flightUpdateBtn.setEnabled(true);
        JOptionPane.showMessageDialog(null, "Account Updated Successfully");

        txtFlightNumber.setEnabled(false);
        txtFrom.setEnabled(false);
        txtTo.setEnabled(false);
        txtDeptTime.setEnabled(false);
        txtArrivalTime.setEnabled(false);
        txtFlightDuration.setEnabled(false);
        txtAirplane.setEnabled(false);
        txtTicketPrice.setEnabled(false);
        txtFlightDate.setEnabled(false);
        txtCrewNumbers.setEnabled(false);
        
        flightSaveBtn.setEnabled(true);
        flightUpdateBtn.setEnabled(false);
    }//GEN-LAST:event_flightSaveBtnActionPerformed

    private void flightUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightUpdateBtnActionPerformed
        // TODO add your handling code here:viewUpdateBtn.setEnabled(false);

        txtFlightNumber.setEnabled(true);
        txtFrom.setEnabled(true);
        txtTo.setEnabled(true);
        txtDeptTime.setEnabled(true);
        txtArrivalTime.setEnabled(true);
        txtFlightDuration.setEnabled(true);
        txtAirplane.setEnabled(true);
        txtTicketPrice.setEnabled(true);
         txtFlightDate.setEnabled(true);
         txtCrewNumbers.setEnabled(true);
        flightSaveBtn.setEnabled(true);
        flightUpdateBtn.setEnabled(false);
    }//GEN-LAST:event_flightUpdateBtnActionPerformed

    private void txtCrewNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrewNumbersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrewNumbersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton flightSaveBtn;
    private javax.swing.JButton flightUpdateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAirplane;
    private javax.swing.JTextField txtArrivalTime;
    private javax.swing.JTextField txtCrewNumbers;
    private javax.swing.JTextField txtDeptTime;
    private javax.swing.JTextField txtFlightDate;
    private javax.swing.JTextField txtFlightDuration;
    private javax.swing.JTextField txtFlightNumber;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtTicketPrice;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
